#pragma once
/// @file Precomputed constants generated by generate_constants.c.
/// Includes bitboard lookup tables, Zobrist hashes, and PEXT attack tables.
/// Do not edit — regenerate with @c make generate_constants.
#include "bitboard.h"
#include "constants.h"
#include <stddef.h>
#include <stdint.h>

/// @brief One square's entry in the PEXT sliding-piece attack table.
/// Uses byte-sized indices to share attack bitboards across occupancy patterns, saving memory.
typedef struct
{
    bitboard_t        occupancy_mask; ///< Relevant occupancy squares for this square (edge squares excluded).
    const bitboard_t *attacks;        ///< Unique attack sets (shared across occupancy patterns).
    const uint8_t    *indices;        ///< Map from pext-compressed occupancy index to attacks[] index.
} pext_bitboard_t;

// ---------------------------------------------------------------------------
// Ray and attack lookup tables (one entry per square)
// ---------------------------------------------------------------------------

extern const bitboard_t NORTH[64];                   ///< All squares north of each square along the file.
extern const bitboard_t NORTHEAST[64];               ///< All squares north-east along the diagonal.
extern const bitboard_t EAST[64];                    ///< All squares east along the rank.
extern const bitboard_t SOUTHEAST[64];               ///< All squares south-east along the anti-diagonal.
extern const bitboard_t SOUTH[64];                   ///< All squares south of each square along the file.
extern const bitboard_t SOUTHWEST[64];               ///< All squares south-west along the anti-diagonal.
extern const bitboard_t WEST[64];                    ///< All squares west along the rank.
extern const bitboard_t NORTHWEST[64];               ///< All squares north-west along the diagonal.
extern const bitboard_t PAWN_ATTACKS_WHITE[64];      ///< Squares a white pawn on each square attacks.
extern const bitboard_t PAWN_ATTACKS_BLACK[64];      ///< Squares a black pawn on each square attacks.
extern const bitboard_t KNIGHT_ATTACKS[64];          ///< All squares a knight on each square attacks.
extern const bitboard_t BISHOP_ATTACKS[64];          ///< All squares a bishop can reach on an empty board.
extern const bitboard_t ROOK_ATTACKS[64];            ///< All squares a rook can reach on an empty board.
extern const bitboard_t QUEEN_ATTACKS[64];           ///< All squares a queen can reach on an empty board.
extern const bitboard_t KING_ATTACKS[64];            ///< All squares a king on each square attacks.
extern const bitboard_t KING_ATTACKS2[64];           ///< Two-step king zone (used for king safety evaluation).
extern const bitboard_t KING_PAWN_SHELTER_WHITE[64]; ///< Pawn-shelter squares for a white king on each square.
extern const bitboard_t KING_PAWN_SHELTER_BLACK[64]; ///< Pawn-shelter squares for a black king on each square.
extern const bitboard_t
    PASSED_PAWN_MASK_WHITE[64]; ///< Squares ahead of a white pawn that must be clear for it to be passed.
extern const bitboard_t
    PASSED_PAWN_MASK_BLACK[64]; ///< Squares ahead of a black pawn that must be clear for it to be passed.
extern const bitboard_t ISOLATED_PAWN_MASK_WHITE[64]; ///< Adjacent files used to detect isolated white pawns.
extern const bitboard_t ISOLATED_PAWN_MASK_BLACK[64]; ///< Adjacent files used to detect isolated black pawns.
extern const bitboard_t
    SUPPORTED_PAWN_MASK_WHITE[64]; ///< Squares from which a white pawn on this square could be supported.
extern const bitboard_t
    SUPPORTED_PAWN_MASK_BLACK[64]; ///< Squares from which a black pawn on this square could be supported.
extern const bitboard_t DOUBLED_PAWN_MASK_WHITE[64]; ///< Squares in front of a white pawn (detects doubled pawns).
extern const bitboard_t DOUBLED_PAWN_MASK_BLACK[64]; ///< Squares in front of a black pawn (detects doubled pawns).

// ---------------------------------------------------------------------------
// Zobrist hashes
// ---------------------------------------------------------------------------

extern const zobrist_t CASTLING_RIGHTS_HASHES[16]; ///< One hash per castling-rights bitmask (0–15).
extern const zobrist_t EN_PASSANT_HASHES[64];      ///< One hash per en-passant target square (index 0 = no ep).

static const zobrist_t BLACK_MOVE_HASH = 0x28AB74D640E50602ull; ///< XOR'd into the hash when it is Black's turn.

// ---------------------------------------------------------------------------
// PEXT sliding-piece attack tables
// ---------------------------------------------------------------------------

extern const pext_bitboard_t BISHOP_PEXTS[64]; ///< PEXT bishop attack table, one entry per square.
extern const pext_bitboard_t ROOK_PEXTS[64];   ///< PEXT rook attack table, one entry per square.

// ---------------------------------------------------------------------------
// Multi-dimensional tables
// ---------------------------------------------------------------------------

/// @brief Squares strictly between any two squares on the same rank, file, or diagonal.
/// Used for pin detection and check-evasion masking.
extern const bitboard_t INTERVENING_SQUARES[64][64];

/// @brief Zobrist hash contributions for each (color, piece, square) triple.
/// Indexed as PIECE_SQUARE_HASHES[color][piece-1][square].
extern const zobrist_t PIECE_SQUARE_HASHES[2][6][64];
